default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finance_api_development
  username: finance_api
  password: F1n@nc3_ap1
  host: localhost
  port: 5432

test:
  <<: *default
  database: finance_api_test
  username: finance_api
  password: F1n@nc3_ap1
  host: localhost
  port: 5432


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # database: finance_api_production
  # username: finance_api
  # password: <%= ENV["FINANCE_API_DATABASE_PASSWORD"] %>
